---
apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"containers.instana.io\":{\"username\":\"_\",\"password\":\"agent_key\",\"auth\":\"XzphZ2VudF9rZXk=\"}}}" | b64enc }}
kind: Secret
metadata:
  name: instana-registry
  namespace: {{ .Values.spec.namespace.operator }}
type: kubernetes.io/dockerconfigjson
---
{{ if and .Values.images.registry.ImagePullSecret.name .Values.images.registry.ImagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}