---
{{ if and .Values.images.registry.ImagePullSecret.server .Values.images.registry.ImagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.spec.namespace.operator }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

---
{{ if and .Values.images.registry.ImagePullSecret.server .Values.images.registry.ImagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.spec.namespace.core }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

---
{{ if and .Values.images.registry.ImagePullSecret.server .Values.images.registry.ImagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.spec.namespace.units }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}