---
apiVersion: v1
data:
  .dockerconfigjson: {{ \{"auths":\{"containers.instana.io":\{"username":"_","password":"agent_key","auth":"XzphZ2VudF9rZXk="\}\}\} |b64enc }}
kind: Secret
metadata:
  name: instana-registry
  namespace: {{ .Values.spec.namespace.operator }}
type: kubernetes.io/dockerconfigjson