apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acceptor
  namespace: instana-core
spec:
  host: agent.instana.{{ .Values.Ingress_Domain }}
  port:
    targetPort: 8600
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: acceptor
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway-core
  namespace: instana-core
spec:
  host: instana.{{ .Values.Ingress_Domain }}
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway-unit
  namespace: instana-core
spec:
  host: prod-instana.instana.{{ .Values.Ingress_Domain }}
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: gateway


