---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-instana-operator
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      containers:
        - name: post-install
          image: quay.io/openshift/origin-cli:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          command:
            - /bin/sh
            - -c
            - |
              #set -o pipefail
              set -x
              result=0
              
              # ocp only below
              version=`oc version |grep Server |awk '{print $3}' |tr -d ' '`
              if [ ${#version} -gt 1 ] ; then
                echo "ocp version ${version} "
              else 
                echo "this is an k8s , no need to execute following commands"
                exit 0
              fi

              echo 'in ocp, add anyuid to instana-operator in instana-operator ...'
              oc adm policy add-scc-to-user anyuid -z instana-operator -n instana-operator
              result=$?
              if [[ ${result} != 0 ]]; then 
                exit "add anyuid to instana-operator exit with ${result}"
              fi



      restartPolicy: Never
      serviceAccountName: default

