apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 239-0
  name: instana-operator-webhook-validating
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lRSEtCMmJGQWdtMjhkcyt3VjlBdlp5REFOQmdrcWhraUc5dzBCQVFzRkFEQWQKTVJzd0dRWURWUVFERXhKcGJuTjBZVzVoTFhkbFltaHZiMnN0WTJFd0hoY05Nak13TVRFMk1URXpNVEF6V2hjTgpNek13TVRFek1URXpNVEF6V2pBZE1Sc3dHUVlEVlFRREV4SnBibk4wWVc1aExYZGxZbWh2YjJzdFkyRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERhM2dlQk0rQkR6ZUM5bC9ua2VFRTB1cnAKUmszVWVWM0p3Tis5cFc5L3RxVURTUXhVUkh3c3FHMk9rQTFSOERyRzlsSVVEK285MDJCRTF1MTJ5cnhRMHZ6eQpFc0M2aERWZzNUM1FSRjJ2Ui8rbHVUVUc3aU1QajM5eUNOZERPTzBpTFZIOHpzdGJVOCsrL1h1ZEV2QVhCZkcvCjFBZlgwbjM2NlRKNjFJcXAvenNPbDQzS21EYmxDMEF3U3AvSWtyQmZsMFNsODU3RWF4RzMzRnJKMkdQVkVNY2oKcytmZ3FaUGdYWFNSQ3BQYUhzOEFUZkZlQWh4WGxwY0xzcFhMRURLUkhPLzBkMnl6RWNISXBxQXB3WE9FWlhqNwp5WC85aDlVbG9RbHozTzBKUFpjdkd1cE1YR3hzMUVWYXJCY1lmWHVxWlZVKzAvRTlzK1MvWWFWWHUrbXpBZ01CCkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUNwREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUIKQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUwNE4xcWZzOFBVSGd2MXU5TUQvOApiZDJZaTU0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEMVB5bW1RWFZpbUN2MmhmUTBUTkR2OUFvUGhoSnZzCjZIRGJ3Vzl3U251VnJVL0I2ZVI0REtHUURyZHRqZFFpdHNkdG5SakUwbDU5RXlSRE5STktUc2hiN1k2SHA4bWsKcm5ENC9xbWNlazRFenBQMkxPdS9hd1JjOG9sbk9nMGJjQ3F1c0pSZDM3cWpGaTJCOXQ2ajdkUmZVVTd1WHhlRgpJNW4xY0QxWlUzWUtLOFFyMG5oMU85M2JCeml2ZVErV1lFTnJBRTBPVnhoSi9TaHpOVGlUV3JnQVhQZTFucWQ3Ck90ZU1SUjVYZDNsSCtFclpvWUR6MkIrWHBLUEI1UlNJVGx0NldMcTgzbVVkLzdWeDFleDlQT01ma2hGOHRyZzkKdnkwc0dOSnArUHVGWk1BcjByY0NHNmZsaDAycnNVQlRMbDl5Skw2bGpaSmI1bnVCaTB6cEZMOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: instana-operator-webhook
        namespace: instana-core
        path: /validate-instana-io-v1beta2-core
    failurePolicy: Fail
    name: vcore.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - cores
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lRSEtCMmJGQWdtMjhkcyt3VjlBdlp5REFOQmdrcWhraUc5dzBCQVFzRkFEQWQKTVJzd0dRWURWUVFERXhKcGJuTjBZVzVoTFhkbFltaHZiMnN0WTJFd0hoY05Nak13TVRFMk1URXpNVEF6V2hjTgpNek13TVRFek1URXpNVEF6V2pBZE1Sc3dHUVlEVlFRREV4SnBibk4wWVc1aExYZGxZbWh2YjJzdFkyRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERhM2dlQk0rQkR6ZUM5bC9ua2VFRTB1cnAKUmszVWVWM0p3Tis5cFc5L3RxVURTUXhVUkh3c3FHMk9rQTFSOERyRzlsSVVEK285MDJCRTF1MTJ5cnhRMHZ6eQpFc0M2aERWZzNUM1FSRjJ2Ui8rbHVUVUc3aU1QajM5eUNOZERPTzBpTFZIOHpzdGJVOCsrL1h1ZEV2QVhCZkcvCjFBZlgwbjM2NlRKNjFJcXAvenNPbDQzS21EYmxDMEF3U3AvSWtyQmZsMFNsODU3RWF4RzMzRnJKMkdQVkVNY2oKcytmZ3FaUGdYWFNSQ3BQYUhzOEFUZkZlQWh4WGxwY0xzcFhMRURLUkhPLzBkMnl6RWNISXBxQXB3WE9FWlhqNwp5WC85aDlVbG9RbHozTzBKUFpjdkd1cE1YR3hzMUVWYXJCY1lmWHVxWlZVKzAvRTlzK1MvWWFWWHUrbXpBZ01CCkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUNwREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUIKQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUwNE4xcWZzOFBVSGd2MXU5TUQvOApiZDJZaTU0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEMVB5bW1RWFZpbUN2MmhmUTBUTkR2OUFvUGhoSnZzCjZIRGJ3Vzl3U251VnJVL0I2ZVI0REtHUURyZHRqZFFpdHNkdG5SakUwbDU5RXlSRE5STktUc2hiN1k2SHA4bWsKcm5ENC9xbWNlazRFenBQMkxPdS9hd1JjOG9sbk9nMGJjQ3F1c0pSZDM3cWpGaTJCOXQ2ajdkUmZVVTd1WHhlRgpJNW4xY0QxWlUzWUtLOFFyMG5oMU85M2JCeml2ZVErV1lFTnJBRTBPVnhoSi9TaHpOVGlUV3JnQVhQZTFucWQ3Ck90ZU1SUjVYZDNsSCtFclpvWUR6MkIrWHBLUEI1UlNJVGx0NldMcTgzbVVkLzdWeDFleDlQT01ma2hGOHRyZzkKdnkwc0dOSnArUHVGWk1BcjByY0NHNmZsaDAycnNVQlRMbDl5Skw2bGpaSmI1bnVCaTB6cEZMOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: instana-operator-webhook
        namespace: instana-core
        path: /validate-instana-io-v1beta2-unit
    failurePolicy: Fail
    name: vunit.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - units
    sideEffects: None
