{{- if not .Values.webhook.caBundleBase64 }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "instana-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
