apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "instana-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
