apiVersion: v1
kind: Service
metadata:
  name: {{ include "instana-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https-webhook
      protocol: TCP
      name: https-webhook
  selector:
    {{- include "instana-operator.selectorLabels" . | nindent 4 }}
