apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "instana-operator.fullname" . }}-mutating
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
  {{- if not .Values.webhook.caBundleBase64 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace}}/{{ include "instana-operator.fullname" . }}-webhook-certs
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- with .Values.webhook.caBundleBase64 }}
      caBundle: {{ . }}
      {{- end }}
      service:
        name: {{ include "instana-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-instana-io-v1beta1-core
    failurePolicy: Fail
    name: mcore.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cores
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "instana-operator.fullname" . }}-validating
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
  {{- if not .Values.webhook.caBundleBase64 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace}}/{{ include "instana-operator.fullname" . }}-webhook-certs
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- with .Values.webhook.caBundleBase64 }}
      caBundle: {{ . }}
      {{- end }}
      service:
        name: {{ include "instana-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-instana-io-v1beta1-core
    failurePolicy: Fail
    name: vcore.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cores
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- with .Values.webhook.caBundleBase64 }}
      caBundle: {{ . }}
      {{- end }}
      service:
        name: {{ include "instana-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-instana-io-v1beta1-unit
    failurePolicy: Fail
    name: vunit.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - units
    sideEffects: None
