kind: Secret
apiVersion: v1
metadata:
  name: instana-pullsecret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
    
type: kubernetes.io/dockerconfigjson
