---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      serviceAccountName: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: {{ .Values.spec.instana_Regisry }}{{.Values.spec.zk_Image}}
        name: zookeeper
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '512m'
            memory: 1Gi
        ports:
          - containerPort: 2181
        volumeMounts:
          - mountPath: /mnt/logs
            name: zookeeper-logs
        securityContext:
          runAsUser: 0
      volumes:
        - name: zookeeper-logs
          persistentVolumeClaim:
            claimName: zookeeper-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.spec.storage_class_block }}
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP