---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      initContainers:
      - image: busybox
        name: cleanup
        resources: {}
        volumeMounts:
          - mountPath: /mnt/data
            name: kafka-data
        command:
          - sh
          - -c
          - "rm -rf /mnt/data/lost+found"
      containers:
      - image:{{ .Values.spec.instana_Regisry }}{{.Values.spec.kafka_Image}}
        name: kafka
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '512m'
            memory: 1Gi
        env:
          - name: ZOOKEEPER_HOST
            value: zookeeper-service
          - name: ADVERTISED_LISTENER
            value: PLAINTEXT://kafka-service.instana-datastores.svc.cluster.local:9092
        ports:
          - containerPort: 9092
        volumeMounts:
          - mountPath: /mnt/log
            name: kafka-logs
          - mountPath: /mnt/data
            name: kafka-data
        securityContext:
          runAsUser: 0
      volumes:
        - name: kafka-logs
          persistentVolumeClaim:
            claimName: kafka-logs
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.spec.storage_class_block }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.spec.storage_class_block }}
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP