---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy: {}
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: instana-datastore-sa
      securityContext:
        fsGroup: 2000
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: {{.Values.image.repo}}"elasticsearch:"{{.Values.image.es_tag}}
        name: elasticsearch
        env:
          - name: LISTEN_ADDR
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
          - containerPort: 9200
            name: elastic-9200
          - containerPort: 9300
            name: elastic-9300
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '512m'
            memory: 1Gi
        volumeMounts:
          - mountPath: /mnt/data
            name: es-data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.storage.sc_block }}
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: elastic-9200
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: elastic-9300
  type: ClusterIP