---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse
  name: clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  strategy: {}
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      serviceAccount: instana-datastore-sa
      securityContext:
        fsGroup: 2000
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: {{.Values.image.repo}}clickhouse:{{.Values.image.clickhouse_tag}}
        name: clickhouse
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '512m'
            memory: 1Gi
        env:
          - name: ZOOKEEPER_HOST
            value: zookeeper-service
        ports:
          - containerPort: 9000
            name: clickhouse-9000
          - containerPort: 8123
            name: clickhouse-8123
        volumeMounts:
          - mountPath: /mnt/data
            name: clickhouse-data
          - mountPath: /mnt/logs
            name: clickhouse-logs
        securityContext:
          runAsUser: 0
          privileged: true
      volumes:
        - name: clickhouse-logs
          persistentVolumeClaim:
            claimName: clickhouse-logs      
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.storage.sc_block }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.storage.sc_block }}
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: clickhouse-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: clickhouse-8123
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: clickhouse-9000
  type: ClusterIP