apiVersion: instana.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{.Values.spec.clusterName}}-instana-provider-config 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{.Values.spec.kubeConfigSecretNS}}
      name: {{.Values.spec.kubeConfigSecretName}}
      key: credentials
