apiVersion: instana.io/v1beta1
kind: Unit
metadata:
  namespace: instana-units
  name: instana-prod
spec:
  coreName: instana-core
  coreNamespace: instana-core
  tenantName: instana
  unitName: prod
  initialAgentKey: {{ .Values.instana_download_key }}
  resourceProfile: small

