apiVersion: batch/v1
kind: Job
metadata:
  name: add-instana-route
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: route
          image: quay.io/openshift/origin-cli:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x
              result=0

              base=`oc get ingresses.config/cluster -o jsonpath={.spec.domain}`
              echo ${base}

              cat << EOF | oc apply -f -
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: acceptor-svc
                namespace: instana-core
              spec:
                host: agent.instana.${base}
                port:
                  targetPort: 8600
                tls:
                  insecureEdgeTerminationPolicy: Redirect
                  termination: passthrough
                to:
                  kind: Service
                  name: acceptor
              EOF
              result=$?
              if [[ ${result} != 0 ]]; then 
                exit "${result}"
              fi              

              cat << EOF | oc apply -f -
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: ingress-core-svc
                namespace: instana-core
              spec:
                host: instana.apps.shul.cp.fyre.ibm.com
                port:
                  targetPort: 8443
                tls:
                  insecureEdgeTerminationPolicy: Redirect
                  termination: passthrough
                to:
                  kind: Service
                  name: ingress-core
                  weight: 100
                wildcardPolicy: None
              EOF
              result=$?
              if [[ ${result} != 0 ]]; then 
                exit "${result}"
              fi                            

              cat << EOF | oc apply -f -
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: unit-ingress-svc
                namespace: instana-units
              spec:
                host: prod-instana.instana.apps.shul.cp.fyre.ibm.com
                port:
                  targetPort: 8443
                tls:
                  insecureEdgeTerminationPolicy: Redirect
                  termination: passthrough
                to:
                  kind: Service
                  name: ingress
              EOF
              result=$?
              if [[ ${result} != 0 ]]; then 
                exit "${result}"
              fi                            

              exit "${result}"
            volumeMounts:
            - mountPath: /root/.kube
              name: kubeconfig              
      restartPolicy: Never
      serviceAccountName: crossplane
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          items:
          - key: credentials
            path: config
          secretName: k8s-kubeconfig