---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: instana-units
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

---
apiVersion: v1
kind: Namespace
  name: {{ .Values.namespace.datastore }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"