---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: instana-units
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.namespace.datastore }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

