---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.namespace.operator }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: instana-units
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
---
{{ if and .Values.images.registry.server .Values.images.registry.ImagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.registry.ImagePullSecret.name }}
  namespace: {{ .Values.namespace.datastore }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: instana-core
  namespace: instana-core
data:
  config.yaml: {{ template "core-Secret" . }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: tenant0-unit0
  namespace: instana-units
data:
  config.yaml: {{ template "tenant0-Secret" . }}
type: Opaque