---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-datastore-sa
  namespace: {{ .Values.namespace.datastore }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instana-datastore-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: instana-datastore-sa
  namespace: {{ .Values.namespace.datastore }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instana-datastore-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: instana-datastore-sa
  namespace: {{ .Values.namespace.datastore }}