---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-instana-route
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      containers:
      - name: job
        image: quay.io/openshift/origin-cli:4.9
        command:
            - /bin/sh
            - -c
            - |
              #set -o pipefail
              set -x
              result=0
              oc login --token=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` --server=https://$KUBERNETES_SERVICE_HOST  --insecure-skip-tls-verify=true
              echo "============ in post-install =========="
              echo "wait until instana-operator pod running"
              while true; do
                if oc get pod -n instana-core | grep -e "^gateway-" | grep Running | grep "1/1"; then
                  echo "instana-gateway pod is running, break wait." 
                  break
                else
                  echo "waiting until instana-gateway pod running ..."
                  sleep 10
                fi
              done
              
              oc -n instana-operator scale --replicas=0  deploy/instana-operator
              oc -n instana-core get cm/gateway -oyaml > /tmp/cm-gw.yaml
              sed -i 's/128/255/g' /tmp/cm-gw.yaml
              oc -n instana-core apply -f /tmp/cm-gw.yaml
              oc -n instana-core get pod  | grep gateway | awk '{print $1}' | xargs oc -n instana-core delete pod

              oc -n instana-operator scale --replicas=1  deploy/instana-operator