---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: patch-instana-route
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "99"
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: openshift-gitops-argocd-application-controller
          containers:
          - name: job
            image: quay.io/openshift/origin-cli:4.9
            command:
            - /bin/sh
            - -c
            - |
              #set -o pipefail
              set -x
              result=0
              oc login --token=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` --server=https://$KUBERNETES_SERVICE_HOST  --insecure-skip-tls-verify=true
              echo "============ in post-install =========="
              echo "wait until instana-operator pod running"
              while true; do
                if oc get pod -n instana-core | grep -e "^gateway-" | grep "0/1" ; then
                  echo "instana-gateway pod is running, break wait." 
                  oc -n instana-operator scale --replicas=0  deploy/instana-operator
                  sleep 5
                  oc -n instana-core get cm/gateway -oyaml > /tmp/cm-gw.yaml
                  sleep 3
                  sed -i 's/128/255/g' /tmp/cm-gw.yaml
                  sleep 3
                  oc -n instana-core apply -f /tmp/cm-gw.yaml
                  sleep 3
                  oc -n instana-core get pod  | grep gateway | awk '{print $1}' | xargs oc -n instana-core delete pod
                  sleep 3
                  oc -n instana-operator scale --replicas=1  deploy/instana-operator
                else
                  echo "waiting until instana-gateway pod running ..."
                  sleep 10
                fi
              done
              
              