apiVersion: instana.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: instana-provider-config 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{.Values.spec.credentials.secretRef.namespace}}
      name: {{.Values.spec.credentials.secretRef.name}}
      key: {{.Values.spec.credentials.secretRef.key}}
