# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: openshift-cert-manager-operator
#   annotations:
#     argocd.argoproj.io/sync-wave: "-10"
# ---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: openshift-operators
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-manager.v1.10.1