# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   labels:
#     app.kubernetes.io/component: webhook
#   name: cert-manager
#   namespace: openshift-operators
#   annotations:
#     "helm.sh/hook": pre-install
#     "helm.sh/hook-weight": "-6"
# spec:
#   channel: stable
#   installPlanApproval: Automatic
#   name: cert-manager
#   source: community-operators
#   sourceNamespace: openshift-marketplace
#   startingCSV: cert-manager.v1.10.1