apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 239-0
  name: instana-operator-leader-election
  namespace: {{ .Values.namespace.operator }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: instana-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: instana-operator
    namespace: {{ .Values.namespace.operator }}
