apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 237-3
  name: instana-operator
  namespace: instana-units
imagePullSecrets:
  - name: instana-registry