apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 237-3
  name: instana-operator-webhook
  namespace: instana-units
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
  type: ClusterIP
