apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: instana-operator/instana-operator-webhook
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 237-3
  name: instana-operator-webhook-validating
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: instana-operator-webhook
        namespace: instana-operator
        path: /validate-instana-io-v1beta2-core
    failurePolicy: Fail
    name: vcore.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - cores
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: instana-operator-webhook
        namespace: instana-operator
        path: /validate-instana-io-v1beta2-unit
    failurePolicy: Fail
    name: vunit.kb.io
    rules:
      - apiGroups:
          - instana.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - units
    sideEffects: None
