{{- if not .Values.webhook.caBundleBase64 }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "instana-operator.fullname" . }}-webhook-certs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
spec:
  subject:
    organizations:
      - instana
  dnsNames:
    - {{ include "instana-operator.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "instana-operator.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ include "instana-operator.fullname" . }}
  secretName: {{ include "instana-operator.fullname" . }}-webhook-certs
{{- end }}
