apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "instana-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "instana-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "instana-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "instana-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
