---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-instance
  namespace: {{.Values.metadata.argocd_app_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: {{.Values.metadata.argocd_app_namespace}}
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
        - /spec/source/repoURL
      kind: Application
  project: default
  source:
    path: config/crossplane
    repoURL: {{.Values.repoURL}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
