apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 239-0
  name: instana-operator-webhook
rules:
  - apiGroups:
      - instana.io
    resources:
      - cores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - instana.io
    resources:
      - datastores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - instana.io
    resources:
      - units
    verbs:
      - get
      - list
      - watch
