apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 239-0
  name: instana-operator-webhook
  namespace: {{ .Values.namespace.operator }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/name: instana
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/name: instana
        app.kubernetes.io/version: 239-0
    spec:
      containers:
        - args:
            - /app/instana-operator-webhook
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: containers.instana.io/instana/release/selfhosted/operator:{{ .Values.images.registry.tag }}
          imagePullPolicy: IfNotPresent
          
          name: instana-operator-webhook
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: cert
              readOnly: true
            - mountPath: /tmp
              name: tmpdir
      enableServiceLinks: false
      imagePullSecrets:
        - name: {{ .Values.images.registry.ImagePullSecret.name }}
      serviceAccountName: instana-operator-webhook
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: instana-operator-webhook
        - emptyDir: {}
          name: tmpdir
