apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 239-0
  name: instana-operator-webhook
  namespace: {{ .Values.namespace.operator }}
